name: Setup
description: Install Dependencies
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
