name: 'Build and push images'
description: 'Build and push container images'
inputs:
  registry:
    description: 'Disco host'
    required: true
  name:
    description: 'Name of container to build'
    required: true
  version:
    description: 'Forta scan node version'
    required: true
outputs:
  release-cid:
    description: 'IPFS CID of the release manifest'
    value: ${{ steps.build-and-push.outputs.release-cid }}
  image-reference:
    description: 'Reference of the built and pushed image'
    value: ${{ steps.build-and-push.outputs.image-reference }}
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build images, prepare manifest and push
      id: build-and-push
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ inputs.name }}
        VERSION: ${{ inputs.version }}
        COMMIT_SHA: ${{ github.sha }}
        RELEASE_NOTES: ${{ github.event.release.body }}
      run: |
        export IMAGE_REF=$(./scripts/docker-build-push.sh "$REGISTRY" "$IMAGE_NAME" "$COMMIT_SHA")
        echo "::set-output name=image-reference::$IMAGE_REF"
        go run scripts/manifest/main.go > manifest.json
        MANIFEST_REF=$(./scripts/ipfs-add.sh "./manifest.json")
        echo "::set-output name=release-cid::$MANIFEST_REF"
