name: Build and Push to Dockerhub

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  IMAGE_NAME: forta-node
  IMAGE_TAG: dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # - name: Set up Go
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: '1.19'

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Generate ghcr.io access token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_2 }}
          owner: Dhuratest
          repositories: "forta-node"
      
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Dhuratest
          password: ${{ steps.generate_token.outputs.token }}

      - name: Build docker image
        id: docker_build_candidate
        uses: docker/build-push-action@v6.1.0
        with:
          file: Dockerfile.node
          push: true
          tags: ghcr.io/dhuratest/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          
