name: E2E Test

on:
  workflow_dispatch:

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        id: setup
        uses: ./.github/actions/setup
      - name: Validate and test Go code
        id: go
        uses: ./.github/actions/go
        with:
          COVERAGE_THRESHOLD: ${{ vars.COVERAGE_THRESHOLD }}

  e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          cache: "false"
      - name: E2E Test
        id: e2e
        uses: ./.github/actions/e2e
