name: Pull Request

on:
  pull_request:

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        id: setup
        uses: ./.github/actions/setup
      - name: Validate and test Go code
        id: go
        uses: ./.github/actions/go
        with:
          COVERAGE_THRESHOLD: ${{ vars.COVERAGE_THRESHOLD }}
